name: "Export binaries"
on: 
  push:
  pull_request:
  workflow_dispatch:

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.6.1
  EXPORT_NAME: SuperMarioWorkerProject2
  PROJECT_PATH: .

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux
          export_template: "Linux"
          ext: "x86_64"
        - name: Windows
          export_template: "Windows Desktop"
          ext: "exe"
        - name: Android
          export_template: "Android"
          ext: "apk"
    runs-on: ubuntu-24.04
    permissions: write-all
    container:
      image: barichello/godot-ci:mono-4.6.1
    name: Export ${{ matrix.name }}
    environment: export
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true
          submodules: true
      - name: Write Decrypt Key
        shell: bash
        run: |
          set -e
          KEY_DIR="content/smwp_1_file_decryptor/key"
          KEY_FILE="$KEY_DIR/smwp1_decrypt_key.txt"
          mkdir -p "$KEY_DIR"
          printf "%s" "${{ secrets.SMWP1_DECRYPT_KEY }}" > "$KEY_FILE.utf8"
          iconv -f UTF-8 -t GB18030 "$KEY_FILE.utf8" -o "$KEY_FILE"
          rm "$KEY_FILE.utf8"
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
          echo "$KEYSTORE" | base64 -d > /root/debug.keystore
        env:
          KEYSTORE: ${{ secrets.SECRET_KEYSTORE_BASE64 }}
      - name: Project Import
        run: |
          cd $PROJECT_PATH
          godot --headless --verbose --import
      - name: Build Godot .NET lib
        run: |
          cd $PROJECT_PATH
          dotnet build
      - name: ${{ matrix.name }} Build
        run: |
          mkdir -v -p "build/${{ matrix.name }}"
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          if [ "${{ matrix.name }}" = "Windows" ]; then
            echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" --rendering-driver opengl3' > "$EXPORT_DIR/${{ matrix.name }}/Compatible_Launch.bat"
          fi
          godot --headless --verbose --export-release "${{ matrix.export_template }}" "${EXPORT_DIR}/${{ matrix.name }}/${EXPORT_NAME}.${{ matrix.ext }}"
          echo "SMWP2 Build: [$(echo "${{ github.sha }}" | cut -c 1-7)](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) from $(date '+%d-%b-%Y %T')" > "$EXPORT_DIR/${{ matrix.name }}/Readme.md"
        env:
          GODOT_ANDROID_KEYSTORE_RELEASE_PATH: "/root/debug.keystore"
          GODOT_ANDROID_KEYSTORE_RELEASE_USER: ${{ secrets.SECRET_KEYSTORE_USER }}
          GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD: ${{ secrets.SECRET_KEYSTORE_PASSWORD }}
          GODOT_ANDROID_KEYSTORE_DEBUG_USER: "androiddebugkey"
          GODOT_ANDROID_KEYSTORE_DEBUG_PASSWORD: "android"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: build/${{ matrix.name }}
